Remove the search plugin to prevent a build error
The search plugin causes this error message:

error: error while generating page "second_part_of_the_second_part/treatise_on_the_cardinal_virtues.md":
RangeError: Maximum call stack size exceeded

According to this page https://github.com/GitbookIO/gitbook/issues/1009, this change will correct the issue.